More debug

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -61,11 +61,11 @@ jobs:
           echo "Root directory:"
           ls -la
           echo "Contents of .next directory:"
-          ls -la .next || echo ".next directory not found"
-            - name: Upload artifact
-              uses: actions/upload-pages-artifact@v1
-              with:
-                path: .
+          ls -la out || echo ".next directory not found"
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v1
+        with:
+          path: ./out
 
   # Deployment job
   deploy:
